version: '3.10.0.{build}'

pull_requests:
  do_not_increment_build_number: true

branches:  
  only:
  - master

configuration: Release

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version} $(APPVEYOR_REPO_COMMIT)"

before_build:
  - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: c18PmLObjM4XzNKNj8/LzYty11gya98+IerJXipzMmL9wgmHS6cGAJWYpJkDxmU2
  on:
    branch: master
    appveyor_repo_tag: true